const SpeedTest = {
    'easy': [
        'cat',
        'dog',
        'father',
        'fighter',
        'hat',
        'dress',
        'adress',
        'local',
        'global',
        'kyle',
        'rat',
        'chicken',
        'google',
        'play',
        'sleep'
    ],
    'normal': [
        'Hello',
        'Programming',
        'Code',
        'JavaScript',
        'Town',
        'Country',
        'Testing',
        'Youtube',
        'Linkedin',
        'Twitter',
        'Github',
        'Leetcode',
        'Internet',
        'Python',
        'Gaming',
        'Styling',
        'Task',
        'Rust',
        'Test',
        'Playing',
        'Runner',
        'Working',
        'Funny',
        'Roles',
        'Dependencies',
        'Iterator',
        'Generate',
        'Scala',
        'Grammer',
        'Laravel'
    ],
    'hard': [
        'function',
        'problem solving',
        'font awesome',
        'good player',
        'hello everyone',
        'have fun',
        'nice day',
        'clean code',
    ]
};


export default SpeedTest;